import { Card } from "@mui/material";

function Container(){
    return (
        <div className="container">
            <Card>
                
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sit amet sagittis tellus. Sed velit dolor, vestibulum sit amet eros ut, imperdiet tincidunt sem. Vivamus congue fringilla mi. Cras accumsan ante vitae lacus pretium, sed auctor massa sodales. Duis egestas fermentum erat, at lobortis purus mattis sit amet. Aenean lacinia metus non lorem auctor, nec volutpat urna semper. Vivamus sit amet vestibulum nibh. Sed in elementum lectus.

Donec consequat est id porttitor feugiat. Fusce eu fringilla nunc, tincidunt condimentum libero. In quis velit et nunc consectetur accumsan non eget orci. Quisque quis rutrum leo, vel convallis eros. Phasellus ullamcorper pulvinar purus, ac porta odio porttitor quis. Vivamus sed volutpat libero, in ultricies elit. Aenean eget tortor eros. Donec molestie urna nec lacus iaculis hendrerit. Donec convallis gravida tortor vitae maximus. Donec porttitor, libero in faucibus dapibus, purus diam interdum elit, eget tincidunt metus lacus et dui. Donec nec leo sollicitudin, cursus ex ac, gravida lacus.

Nam ultrices quam non neque varius dapibus. Aliquam eget mi hendrerit, placerat risus vel, aliquam est. Etiam hendrerit finibus dapibus. Sed vel dapibus nulla. Praesent a congue neque, quis bibendum velit. Fusce viverra lorem sit amet est gravida, varius hendrerit eros scelerisque. Nulla sollicitudin vitae mauris quis hendrerit. Aenean accumsan, massa eu rhoncus mollis, enim nisl mattis nisi, eu efficitur nibh mi nec justo. Suspendisse facilisis augue metus, mollis rhoncus mauris lacinia id. Donec consectetur justo sed mollis sollicitudin. In leo neque, gravida eu urna vehicula, ultrices hendrerit urna. Vivamus et elit libero. Curabitur semper feugiat erat at feugiat.

Proin fermentum sapien a est blandit viverra. Proin et enim ante. Curabitur ex risus, efficitur id ornare eu, congue eu eros. Maecenas bibendum, lacus at aliquam vulputate, mi dolor egestas nibh, sed dictum odio velit quis arcu. In fringilla, tellus a tristique pulvinar, velit urna euismod lorem, a convallis risus diam vel magna. Cras vel convallis ex. Etiam non elementum mi, et ultricies enim. Fusce pellentesque sit amet tellus at posuere.

In hac habitasse platea dictumst. Curabitur facilisis nisl nisi, venenatis congue diam mollis et. Fusce dapibus dignissim tellus, tristique vulputate tellus posuere condimentum. Vestibulum sollicitudin, ligula at ultricies gravida, tellus massa semper felis, ut bibendum tortor elit vitae erat. Morbi lacinia turpis augue, sit amet venenatis nisl elementum sed. Aliquam erat volutpat. Nunc pellentesque sapien vel tempor fermentum. Donec hendrerit consequat enim eu placerat. Quisque purus justo, fringilla non diam sit amet, finibus aliquam dui. Cras vitae lacus egestas, congue augue in, interdum risus. Curabitur pellentesque lorem ut euismod congue. Nulla elementum ex metus, eu scelerisque augue pulvinar eu. Nulla in velit placerat, laoreet nunc eu, dignissim nisl. Morbi porta ipsum id diam semper, ut maximus sem mollis. Curabitur non augue ac arcu aliquam feugiat. Nulla in elit tincidunt nisl consequat facilisis sed nec mauris.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sit amet sagittis tellus. Sed velit dolor, vestibulum sit amet eros ut, imperdiet tincidunt sem. Vivamus congue fringilla mi. Cras accumsan ante vitae lacus pretium, sed auctor massa sodales. Duis egestas fermentum erat, at lobortis purus mattis sit amet. Aenean lacinia metus non lorem auctor, nec volutpat urna semper. Vivamus sit amet vestibulum nibh. Sed in elementum lectus.

Donec consequat est id porttitor feugiat. Fusce eu fringilla nunc, tincidunt condimentum libero. In quis velit et nunc consectetur accumsan non eget orci. Quisque quis rutrum leo, vel convallis eros. Phasellus ullamcorper pulvinar purus, ac porta odio porttitor quis. Vivamus sed volutpat libero, in ultricies elit. Aenean eget tortor eros. Donec molestie urna nec lacus iaculis hendrerit. Donec convallis gravida tortor vitae maximus. Donec porttitor, libero in faucibus dapibus, purus diam interdum elit, eget tincidunt metus lacus et dui. Donec nec leo sollicitudin, cursus ex ac, gravida lacus.

Nam ultrices quam non neque varius dapibus. Aliquam eget mi hendrerit, placerat risus vel, aliquam est. Etiam hendrerit finibus dapibus. Sed vel dapibus nulla. Praesent a congue neque, quis bibendum velit. Fusce viverra lorem sit amet est gravida, varius hendrerit eros scelerisque. Nulla sollicitudin vitae mauris quis hendrerit. Aenean accumsan, massa eu rhoncus mollis, enim nisl mattis nisi, eu efficitur nibh mi nec justo. Suspendisse facilisis augue metus, mollis rhoncus mauris lacinia id. Donec consectetur justo sed mollis sollicitudin. In leo neque, gravida eu urna vehicula, ultrices hendrerit urna. Vivamus et elit libero. Curabitur semper feugiat erat at feugiat.

Proin fermentum sapien a est blandit viverra. Proin et enim ante. Curabitur ex risus, efficitur id ornare eu, congue eu eros. Maecenas bibendum, lacus at aliquam vulputate, mi dolor egestas nibh, sed dictum odio velit quis arcu. In fringilla, tellus a tristique pulvinar, velit urna euismod lorem, a convallis risus diam vel magna. Cras vel convallis ex. Etiam non elementum mi, et ultricies enim. Fusce pellentesque sit amet tellus at posuere.

In hac habitasse platea dictumst. Curabitur facilisis nisl nisi, venenatis congue diam mollis et. Fusce dapibus dignissim tellus, tristique vulputate tellus posuere condimentum. Vestibulum sollicitudin, ligula at ultricies gravida, tellus massa semper felis, ut bibendum tortor elit vitae erat. Morbi lacinia turpis augue, sit amet venenatis nisl elementum sed. Aliquam erat volutpat. Nunc pellentesque sapien vel tempor fermentum. Donec hendrerit consequat enim eu placerat. Quisque purus justo, fringilla non diam sit amet, finibus aliquam dui. Cras vitae lacus egestas, congue augue in, interdum risus. Curabitur pellentesque lorem ut euismod congue. Nulla elementum ex metus, eu scelerisque augue pulvinar eu. Nulla in velit placerat, laoreet nunc eu, dignissim nisl. Morbi porta ipsum id diam semper, ut maximus sem mollis. Curabitur non augue ac arcu aliquam feugiat. Nulla in elit tincidunt nisl consequat facilisis sed nec mauris.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sit amet sagittis tellus. Sed velit dolor, vestibulum sit amet eros ut, imperdiet tincidunt sem. Vivamus congue fringilla mi. Cras accumsan ante vitae lacus pretium, sed auctor massa sodales. Duis egestas fermentum erat, at lobortis purus mattis sit amet. Aenean lacinia metus non lorem auctor, nec volutpat urna semper. Vivamus sit amet vestibulum nibh. Sed in elementum lectus.

Donec consequat est id porttitor feugiat. Fusce eu fringilla nunc, tincidunt condimentum libero. In quis velit et nunc consectetur accumsan non eget orci. Quisque quis rutrum leo, vel convallis eros. Phasellus ullamcorper pulvinar purus, ac porta odio porttitor quis. Vivamus sed volutpat libero, in ultricies elit. Aenean eget tortor eros. Donec molestie urna nec lacus iaculis hendrerit. Donec convallis gravida tortor vitae maximus. Donec porttitor, libero in faucibus dapibus, purus diam interdum elit, eget tincidunt metus lacus et dui. Donec nec leo sollicitudin, cursus ex ac, gravida lacus.

Nam ultrices quam non neque varius dapibus. Aliquam eget mi hendrerit, placerat risus vel, aliquam est. Etiam hendrerit finibus dapibus. Sed vel dapibus nulla. Praesent a congue neque, quis bibendum velit. Fusce viverra lorem sit amet est gravida, varius hendrerit eros scelerisque. Nulla sollicitudin vitae mauris quis hendrerit. Aenean accumsan, massa eu rhoncus mollis, enim nisl mattis nisi, eu efficitur nibh mi nec justo. Suspendisse facilisis augue metus, mollis rhoncus mauris lacinia id. Donec consectetur justo sed mollis sollicitudin. In leo neque, gravida eu urna vehicula, ultrices hendrerit urna. Vivamus et elit libero. Curabitur semper feugiat erat at feugiat.

Proin fermentum sapien a est blandit viverra. Proin et enim ante. Curabitur ex risus, efficitur id ornare eu, congue eu eros. Maecenas bibendum, lacus at aliquam vulputate, mi dolor egestas nibh, sed dictum odio velit quis arcu. In fringilla, tellus a tristique pulvinar, velit urna euismod lorem, a convallis risus diam vel magna. Cras vel convallis ex. Etiam non elementum mi, et ultricies enim. Fusce pellentesque sit amet tellus at posuere.

In hac habitasse platea dictumst. Curabitur facilisis nisl nisi, venenatis congue diam mollis et. Fusce dapibus dignissim tellus, tristique vulputate tellus posuere condimentum. Vestibulum sollicitudin, ligula at ultricies gravida, tellus massa semper felis, ut bibendum tortor elit vitae erat. Morbi lacinia turpis augue, sit amet venenatis nisl elementum sed. Aliquam erat volutpat. Nunc pellentesque sapien vel tempor fermentum. Donec hendrerit consequat enim eu placerat. Quisque purus justo, fringilla non diam sit amet, finibus aliquam dui. Cras vitae lacus egestas, congue augue in, interdum risus. Curabitur pellentesque lorem ut euismod congue. Nulla elementum ex metus, eu scelerisque augue pulvinar eu. Nulla in velit placerat, laoreet nunc eu, dignissim nisl. Morbi porta ipsum id diam semper, ut maximus sem mollis. Curabitur non augue ac arcu aliquam feugiat. Nulla in elit tincidunt nisl consequat facilisis sed nec mauris.
            </Card>
        </div>
    )
}

export default Container;